name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build package
      run: npm run build
    
    - name: Create dist folder
      run: |
        mkdir -p dist
        cp -r src/* dist/
        cp package.json dist/
    
    - name: Upload dist as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: dist/
